[workspace]

members = ["task-maker-*"]

[package]
name = "task-maker-rust"
version = "0.3.9"
description = "Tool for building tasks for informatics competitions, with support for cache, distributed computations and more"
readme = "README.md"
authors = ["Edoardo Morassutto <edoardo.morassutto@gmail.com>"]
edition = "2018"
documentation = "https://edomora97.github.io/task-maker-rust/"
repository = "https://github.com/edomora97/task-maker-rust"
license = "MPL-2.0"

[package.metadata.deb]
extended-description = "Tool for building tasks for informatics competitions, with support for cache, distributed computations and more"
assets = [
    # main executable
    ["target/release/task-maker", "usr/bin/task-maker-rust", "755"],
    # autocompletion files
    ["target/autocompletion/task-maker-rust.bash", "etc/bash_completion.d/task-maker-rust", "644"],
    ["target/autocompletion/_task-maker-rust", "usr/share/zsh/vendor-completions/_task-maker-rust", "644"],
    ["target/autocompletion/task-maker-rust.fish", "usr/share/fish/completions/task-maker-rust.fish", "644"],
    # runtime required data
    ["data/**/*", "usr/share/task-maker-rust/", "755"],
    # vim syntax highlight
    ["tools/vim/ftdetect/cases_gen.vim", "usr/share/vim/vimfiles/ftdetect/cases_gen.vim", "644"],
    ["tools/vim/syntax/cases_gen.vim", "usr/share/vim/vimfiles/syntax/cases_gen.vim", "644"],
]

[badges]
travis-ci = { repository = "edomora97/task-maker-rust" }

[dependencies]
task-maker-dag = { path = "./task-maker-dag" }
task-maker-store = { path = "./task-maker-store" }
task-maker-cache = { path = "./task-maker-cache" }
task-maker-exec = { path = "./task-maker-exec" }
task-maker-format = { path = "./task-maker-format" }
log = "0.4"
env_logger = "0.6"
tempdir = "0.3"
structopt = "0.3"
num_cpus = "1.10"
better-panic = "0.2"
whoami = "0.6"
directories = "3.0"
failure = "0.1"
serde = "1.0"
serde_json = "1.0"
tabox = "0.1"
ctrlc = "3.1"
lazy_static = "1.4"
itertools = "0.8"
walkdir = "2.3"
scopeguard = "1.0"

[[bin]]
name = "task-maker"
path = "src/main.rs"

[[bin]]
name = "task-maker-gen-autocompletion"
path = "src/gen_autocompletion.rs"