# Testing the release process is a nasty process since release.yml is triggered
# when a release is created. Creating a release will send an email to all the
# users watching the repo. To avoid spamming those uses with "test releases" we
# can manually trigger the build process and simply avoid publishing the
# release.

name: Manual Release Test

on: workflow_dispatch

jobs:
  deb:
    name: Debian/Ubuntu (deb)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build deb file
        run: |
          docker run --rm -v $(pwd):/source ghcr.io/edomora97/task-maker-rust-release-linux
      - name: Upload the artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Ubuntu deb
          path: "target/debian/*.deb"

  aur:
    name: AUR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build PKGBUILD
        working-directory: tools/aur/task-maker-rust
        run: ./gen.sh > ../../../PKGBUILD
  ## Commented out since it doesn't support dry-run.
  #     - name: Publish PKGBUILD
  #       uses: KSXGitHub/github-actions-deploy-aur@v2.7.0
  #       with:
  #         pkgname: task-maker-rust
  #         pkgbuild: ./PKGBUILD
  #         commit_username: ${{ secrets.AUR_USERNAME }}
  #         commit_email: ${{ secrets.AUR_EMAIL }}
  #         ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}

  # Do not trigger the PPA rebuilding for this test.
  # ppa:
  #   name: Publish PPA
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Trigger PPA build
  #       env:
  #         GH_TOKEN: ${{ secrets.PAT_PPA_ACTION_TRIGGER }}
  #       run: |
  #         gh workflow run -R dp1/task-maker-rust-ppa --ref master check-for-release.yml
